server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql:///todo-list
    username: quinn
    password: quinn
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
